version: "3.3"

services:
  app:
    container_name: lucy-frontend
    image: lucy-frontend
    build:
      context: .
      dockerfile: 'Dockerfile'
    volumes:
      - ./src:/app/src
    ports:
      - 4001:3000

