export const FIND_CHANGE_PASSWORD_LIST = 'FIND_CHANGE_PASSWORD_LIST';
export const FIND_CHANGE_PASSWORD_LIST_SUCCESS = 'FIND_CHANGE_PASSWORD_LIST_SUCCESS';
export const FIND_CHANGE_PASSWORD_LIST_ERROR = 'FIND_CHANGE_PASSWORD_LIST_ERROR';

export const CONFIGURE_CHANGE_PASSWORD = 'CONFIGURE_CHANGE_PASSWORD';
export const CONFIGURE_CHANGE_PASSWORD_SUCCESS = 'CONFIGURE_CHANGE_PASSWORD_SUCCESS';
export const CONFIGURE_CHANGE_PASSWORD_ERROR = 'CONFIGURE_CHANGE_PASSWORD_ERROR';

export const GET_CHANGE_PASSWORD_BY_ID = 'GET_CHANGE_PASSWORD_BY_ID';
export const GET_CHANGE_PASSWORD_BY_ID_SUCCESS = 'GET_CHANGE_PASSWORD_BY_ID_SUCCESS';
export const GET_CHANGE_PASSWORD_BY_ID_ERROR = 'GET_CHANGE_PASSWORD_BY_ID_ERROR';

export const INACTIVE_CHANGE_PASSWORD = 'INACTIVE_CHANGE_PASSWORD';
export const INACTIVE_CHANGE_PASSWORD_SUCCESS = 'INACTIVE_CHANGE_PASSWORD_SUCCESS';
export const INACTIVE_CHANGE_PASSWORD_ERROR = 'INACTIVE_CHANGE_PASSWORD_ERROR';

export const GET_ACTIVE_LIST_CHANGE_PASSWORD = 'GET_ACTIVE_LIST_CHANGE_PASSWORD';
export const GET_ACTIVE_LIST_CHANGE_PASSWORD_SUCCESS = 'GET_ACTIVE_LIST_CHANGE_PASSWORD_SUCCESS';
export const GET_ACTIVE_LIST_CHANGE_PASSWORD_ERROR = 'GET_ACTIVE_LIST_CHANGE_PASSWORD_ERROR';

//getListRequestChangePassword
export const GET_LIST_REQUEST_CHANGE_PASSWORD = 'GET_LIST_REQUEST_CHANGE_PASSWORD';
export const GET_LIST_REQUEST_CHANGE_PASSWORD_SUCCESS = 'GET_LIST_REQUEST_CHANGE_PASSWORD_SUCCESS';
export const GET_LIST_REQUEST_CHANGE_PASSWORD_ERROR = 'GET_LIST_REQUEST_CHANGE_PASSWORD_ERROR';

export const SET_CHANGE_PASSWORD = 'SET_CHANGE_PASSWORD';


/******************************
 * Manejo de cambios de clave *
 *******************************/

export const configureChangePassword = (changePassword, ownProps, onSuccess) => ({
  type: CONFIGURE_CHANGE_PASSWORD,
  changePassword,
  ownProps,
  onSuccess,
});

export const configureChangePasswordSuccess = () => ({
  type: CONFIGURE_CHANGE_PASSWORD_SUCCESS,
});

export const configureChangePasswordError = (error) => ({
  type: CONFIGURE_CHANGE_PASSWORD_ERROR,
  error,
});

export const setChangePassword = (changePassword) => ({
  type: SET_CHANGE_PASSWORD,
  changePassword,
});
